version: '3'

services:
  device-host:
    container_name: device-host
    hostname: device-host
    image: casanode${REPOSITORY_ADDENDUM}/device-host:${TAG}-2.0.1
    volumes:
      - /usr/local/casa/applications/.env:/usr/local/casa/applications/.env
    network_mode: "host"
